### ISSUE TITLE
Filtering Implementation

### ISSUE THREAD

**Issue by jamesdixon** [kideh88/node-jsonapi-query-parser#1]
Hi,

Great library! 

I had actually hacked something together when I first started build out JSONAPI-based API, but I came across your library and liked it better than what I had written.

That said, the one key item missing is filtering as you already know. It doesn't seem like the JSONAPI spec is going to enforce a particular filtering strategy any time soon. I peeked at the 1.1 spec and filtering is still agnostic. [This thread on the JSONAPI discussion board](http://discuss.jsonapi.org/t/share-propose-a-filtering-strategy/257/) also seems to point to the JSONAPI maintainers not focusing on that part of the spec at this point. There were some suggestions on recommended filtering strategies, such as using the OData spec, which is powerful, but honestly probably a bit too much initially. In my implementation, I had taken the approach of allowing simple equality filtering on attributes. So for example, if you had a collection of `users` with a `firstName` attribute, you could filter all users with the name James using  `/users?filter[firstName]=James`.

I'm not sure if you're using a front-end framework, but I use Ember, which is one of the better implementations of consuming JSONAPI and it uses this filtering approach (at least for now).

All that said, would you be open to adding support for passing filters in the hash format and then converting to an object (like you do with fields)? I think that would allow some flexibility in how people deal with filtering.

Thanks!
James

**Comment by kideh88** [comment]
Hi!
Thanks :)
I am actually in the process of making a whole other solution that allows filters and will take care of body data validation too! (Including things like checking mismatch of the body data resource type to the endpoint resource type)
For now i can quickly add the filter parsing the fields parameter uses.
Happy coding!
Kim

**Comment by jamesdixon** [comment]
Thanks, Kim. Will your new solution be part of this project? The reason i ask is because I like the fact that this project does a single thing and does it well.

**Comment by kideh88** [comment]
New solution will be in its own repository. Its a complete remake with a tokenization/compiler-like approach.
So no worries, I'll keep this one simple like now!

**Comment by jamesdixon** [comment]
Awesome! Great work!

**Comment by kideh88** [comment]
Custom filter implementation in [1.2.0](https://github.com/kideh88/node-jsonapi-query-parser/tree/1.2.0)
Acting like fields: &filter[name]=john%20doe&filter[age]=25
filter: {
  name: 'john%20doe',
  age: '15'
}

**Comment by jamesdixon** [comment]
Thanks! Will you be publishing to npm?

**Comment by jamesdixon** [comment]
Disregard that last comment :+1: Great work -- thanks for the quick turnaround!

**Comment by kideh88** [comment]
Thanks and no problem, report more if you find any other issues!
Also thanks for linking that filter discussion thread, helped me with some issues on my other solution
