### ISSUE TITLE
Filter is not working

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [kideh88/node-jsonapi-query-parser#15]
There are several problems reported in these same conditions.

How much will the filter be working? I used the example of the documentation and the result was different from what is expected

```
?filter[name]=john%20doe&&filter[age][lt]=15
```

![captura de tela 2019-02-17 as 14 46 32](https://user-images.githubusercontent.com/22005684/52916810-de87d980-32c2-11e9-825e-feb68911cf8e.png)

**Comment by alechirsch** [comment]
Hey, try this instead '?filter[name]=john%20doe&&filter[lt][age]=15'

**Comment by alechirsch** [comment]
The documentation is incorrect

**Comment by carvalhoviniciusluiz** [comment]
Now, thank you very much :))

this should be corrected in the documentation to make it more consistent.
