### ISSUE TITLE
Sort string converted to lowercase causing issue

### ISSUE THREAD

**Issue by jamesdixon** [kideh88/node-jsonapi-query-parser#2]
Hi,

When you parse the sort string, it's being converted to all lowercase. I think the casing should be left intact as some systems are case sensitive. For example, I have to convert `camelCase` values to `snake_case`. When I pass `?sort=userId`, the param is converted to `userid`, which doesn't allow me to convert it to `snake_case`.

Thanks!
James

**Comment by kideh88** [comment]
Ah yes, did lower case to be sure the replacer hits, i'll do with a split instead

**Comment by kideh88** [comment]
Fixed in [1.2.0](https://github.com/kideh88/node-jsonapi-query-parser/tree/1.2.0)

**Comment by jamesdixon** [comment]
Thanks :+1:
